name: Test on macOS

on:
  workflow_dispatch:
  workflow_call:

jobs:
  macos:
    strategy:
      matrix:
        macos-version: ["13", "14"]
      fail-fast: false

    name: Test macOS ${{ matrix.macos-version }}
    runs-on: macos-${{ matrix.macos-version }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: angr
      - uses: actions/checkout@v4
        with:
          repository: angr/binaries
          path: binaries
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: python -m venv $HOME/venv
        name: Create venv
        shell: bash
      - run: |
          source $HOME/venv/bin/activate
          pip install "setuptools>=59" wheel cffi "unicorn==2.0.1.post1"
          pip install git+https://github.com/angr/archinfo.git
          pip install git+https://github.com/angr/pyvex.git
          pip install git+https://github.com/angr/cle.git
          pip install git+https://github.com/angr/claripy.git
          pip install git+https://github.com/angr/ailment.git
        name: Install dependencies
      - run: |
          source $HOME/venv/bin/activate
          pip install --no-build-isolation ./angr[testing]
        name: Install angr
      - run: |
          source $HOME/venv/bin/activate
          pytest -n auto angr
        name: Run pytest
